// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ContentUnderstandingClient } from "./contentUnderstandingClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  ContentAnalyzerOperationStatus,
  OperationState,
  ContentAnalyzer,
  ResourceStatus,
  ContentAnalyzerConfig,
  TableFormat,
  ChartFormat,
  AnnotationFormat,
  ContentCategoryDefinition,
  ContentFieldSchema,
  ContentFieldDefinition,
  GenerationMethod,
  ContentFieldType,
  ProcessingLocation,
  KnowledgeSource,
  KnowledgeSourceUnion,
  KnowledgeSourceKind,
  LabeledDataKnowledgeSource,
  SupportedModels,
  UsageDetails,
  AnalyzeInput,
  AnalyzeResult,
  StringEncoding,
  MediaContent,
  MediaContentUnion,
  MediaContentKind,
  ContentField,
  ContentFieldUnion,
  ContentSpan,
  StringField,
  DateField,
  TimeField,
  NumberField,
  IntegerField,
  BooleanField,
  ArrayField,
  ObjectField,
  JsonField,
  DocumentContent,
  LengthUnit,
  DocumentPage,
  DocumentWord,
  DocumentLine,
  DocumentBarcode,
  DocumentBarcodeKind,
  DocumentFormula,
  DocumentFormulaKind,
  DocumentParagraph,
  SemanticRole,
  DocumentSection,
  DocumentTable,
  DocumentTableCell,
  DocumentTableCellKind,
  DocumentCaption,
  DocumentFootnote,
  DocumentFigure,
  DocumentFigureUnion,
  DocumentFigureKind,
  DocumentChartFigure,
  DocumentMermaidFigure,
  DetectedPerson,
  DocumentAnnotation,
  DocumentAnnotationKind,
  DocumentAnnotationComment,
  DocumentHyperlink,
  DocumentContentSegment,
  AudioVisualContent,
  TranscriptPhrase,
  TranscriptWord,
  AudioVisualContentSegment,
  ContentAnalyzerAnalyzeOperationStatus,
  CopyAuthorization,
  ContentUnderstandingDefaults,
  KnownVersions,
} from "./models/index.js";
export { ContentUnderstandingClientOptionalParams } from "./api/index.js";
export {
  ContentAnalyzersUpdateDefaultsOptionalParams,
  ContentAnalyzersGetDefaultsOptionalParams,
  ContentAnalyzersGrantCopyAuthorizationOptionalParams,
  ContentAnalyzersCopyOptionalParams,
  ContentAnalyzersDeleteResultOptionalParams,
  ContentAnalyzersGetResultFileOptionalParams,
  ContentAnalyzersGetResultOptionalParams,
  ContentAnalyzersAnalyzeBinaryOptionalParams,
  ContentAnalyzersAnalyzeOptionalParams,
  ContentAnalyzersListOptionalParams,
  ContentAnalyzersDeleteOptionalParams,
  ContentAnalyzersGetOptionalParams,
  ContentAnalyzersUpdateOptionalParams,
  ContentAnalyzersCreateOrReplaceOptionalParams,
  ContentAnalyzersGetOperationStatusOptionalParams,
} from "./api/contentAnalyzers/index.js";
export { ContentAnalyzersOperations } from "./classic/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
