// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  PageSettings,
  ContinuablePage,
  PagedAsyncIterableIterator,
} from "./static-helpers/pagingHelpers.js";

export { ContentUnderstandingClient } from "./contentUnderstandingClient.js";
export { restorePoller, RestorePollerOptions } from "./restorePollerHelpers.js";
export {
  AnalyzeInput,
  OperationState,
  AnalyzeResult,
  StringEncoding,
  MediaContent,
  MediaContentUnion,
  MediaContentKind,
  ContentField,
  ContentFieldUnion,
  ContentFieldType,
  ContentSpan,
  StringField,
  DateField,
  TimeField,
  NumberField,
  IntegerField,
  BooleanField,
  ArrayField,
  ObjectField,
  JsonField,
  DocumentContent,
  LengthUnit,
  DocumentPage,
  DocumentWord,
  DocumentLine,
  DocumentBarcode,
  DocumentBarcodeKind,
  DocumentFormula,
  DocumentFormulaKind,
  DocumentParagraph,
  SemanticRole,
  DocumentSection,
  DocumentTable,
  DocumentTableCell,
  DocumentTableCellKind,
  DocumentCaption,
  DocumentFootnote,
  DocumentFigure,
  DocumentFigureUnion,
  DocumentFigureKind,
  DocumentChartFigure,
  DocumentMermaidFigure,
  DetectedPerson,
  DocumentAnnotation,
  DocumentAnnotationKind,
  DocumentAnnotationComment,
  DocumentHyperlink,
  DocumentContentSegment,
  AudioVisualContent,
  TranscriptPhrase,
  TranscriptWord,
  AudioVisualContentSegment,
  ContentAnalyzerAnalyzeOperationStatus,
  UsageDetails,
  ContentAnalyzer,
  ResourceStatus,
  ContentAnalyzerConfig,
  TableFormat,
  ChartFormat,
  AnnotationFormat,
  ContentCategoryDefinition,
  ContentFieldSchema,
  ContentFieldDefinition,
  GenerationMethod,
  ProcessingLocation,
  KnowledgeSource,
  KnowledgeSourceUnion,
  KnowledgeSourceKind,
  LabeledDataKnowledgeSource,
  SupportedModels,
  ContentAnalyzerOperationStatus,
  ContentUnderstandingDefaults,
  CopyAuthorization,
  KnownVersions,
} from "./models/index.js";
export {
  ContentUnderstandingClientOptionalParams,
  UpdateDefaultsOptionalParams,
  UpdateOptionalParams,
  ListOptionalParams,
  GrantCopyAuthorizationOptionalParams,
  GetResultFileOptionalParams,
  GetResultOptionalParams,
  GetOperationStatusOptionalParams,
  GetDefaultsOptionalParams,
  GetOptionalParams,
  DeleteResultOptionalParams,
  DeleteOptionalParams,
  CreateOrReplaceOptionalParams,
  CopyOptionalParams,
  AnalyzeBinaryOptionalParams,
  AnalyzeOptionalParams,
} from "./api/index.js";
export { PageSettings, ContinuablePage, PagedAsyncIterableIterator };
